WIP [NDEV-1149] Generate a fake block hash for slots that aren't in the current bank fork
neonevm/neon-evm pull request #851
Opened 2023-01-19 13:45 UTC by Denommus

2023-02-06 17:12 UTC, dk-neon requested changes

2023-02-06 17:24 UTC, Denommus commented on evm_loader/flake.nix
> +{
This file and the file.lock are a proposal to support Nix environments (since I use them myself in my workstation).

2023-02-06 17:25 UTC, Denommus commented on evm_loader/program/src/account_storage/mod.rs
> +    for i in 0..non_null_len {
I cannot, the lengths of both slices need to be the same to use `clone_from_slice`, and they are not.

2023-02-06 17:35 UTC, dk-neon commented on evm_loader/program/src/account_storage/mod.rs
> +    for i in 0..non_null_len {
I mean, you can copy one full slice to sub-slice of the another slice.

2023-02-06 18:09 UTC, Denommus commented on evm_loader/program/src/account_storage/mod.rs
> +    for i in 0..non_null_len {
I'll see!

2023-02-06 18:44 UTC, Denommus commented on evm_loader/program/src/account_storage/mod.rs
> +    for i in 0..non_null_len {
Done.

2023-02-07 14:07 UTC, dk-neon requested changes

2023-02-07 14:07 UTC, dk-neon commented on evm_loader/program/src/account_storage/mod.rs
> +    let slot_vec: Vec<_> = std::iter::once(0)
I think, it also could be cheaper not to create temporary vector, but just use in `copy_from_slice` sub-slice from `slot_bytes`, started from non-zero.

2023-02-08 18:38 UTC, closed without merging